### ISSUE TITLE
luigi v02 pipeline: make HGMD path optional 

### ISSUE THREAD

**Issue by bw2** [broadinstitute/hail-elasticsearch-pipelines#151]
Currently if `hgmd_ht_path` isn't set, or is set to empty string, I get errors like
```
ERROR: [pid 12013] Worker Worker(salt=203839206, workers=1, host=seqr-install-ubuntu, username=weisburd, pid=12013) failed    SeqrVCFToMTTask(source_paths=["./tests/data/1kg_30variants.vcf.bgz"], dest_path=test.mt, genome_version=37, vep_runner=VEP, reference_ht_path=gs://seqr-reference-data/GRCh37/all_reference_data/combined_reference_data_grch37.ht, clinvar_ht_path=gs://seqr-reference-data/GRCh37/clinvar/clinvar.GRCh37.ht, hgmd_ht_path=, sample_type=WGS, validate=False, dataset_type=VARIANTS, remap_path=./tests/data/remap_testing.tsv, subset_path=./tests/data/subset_testing.tsv)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.6/dist-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "seqr_loading.py", line 45, in run
    hgmd = hl.read_table(self.hgmd_ht_path)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-1204>", line 2, in read_table
  File "/usr/local/lib/python3.6/dist-packages/hail/typecheck/check.py", line 585, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/usr/local/lib/python3.6/dist-packages/hail/methods/impex.py", line 2196, in read_table
    return Table(TableRead(tr, False))
  File "/usr/local/lib/python3.6/dist-packages/hail/table.py", line 336, in __init__
    self._type = self._tir.typ
  File "/usr/local/lib/python3.6/dist-packages/hail/ir/base_ir.py", line 142, in typ
    self._compute_type()
  File "/usr/local/lib/python3.6/dist-packages/hail/ir/table_ir.py", line 201, in _compute_type
    self._type = Env.backend().table_type(self)
  File "/usr/local/lib/python3.6/dist-packages/hail/backend/backend.py", line 119, in table_type
    jir = self._to_java_ir(tir)
  File "/usr/local/lib/python3.6/dist-packages/hail/backend/backend.py", line 104, in _to_java_ir
    ir._jir = ir.parse(r(ir), ir_map=r.jirs)
  File "/usr/local/lib/python3.6/dist-packages/hail/ir/base_ir.py", line 147, in parse
    return Env.hail().expr.ir.IRParser.parse_table_ir(code, ref_map, ir_map)
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.6/dist-packages/hail/utils/java.py", line 221, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: IllegalArgumentException: Can not create a Path from an empty string

Java stack trace:
java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:126)
	at org.apache.hadoop.fs.Path.<init>(Path.java:134)
	at is.hail.io.fs.HadoopFS.is$hail$io$fs$HadoopFS$$_fileSystem(HadoopFS.scala:156)
	at is.hail.io.fs.HadoopFS.isDir(HadoopFS.scala:173)
	at is.hail.variant.RelationalSpec$.read(MatrixTable.scala:39)
	at is.hail.expr.ir.TableNativeReader.spec$lzycompute(TableIR.scala:138)
	at is.hail.expr.ir.TableNativeReader.spec(TableIR.scala:135)
	at is.hail.expr.ir.TableNativeReader.fullType(TableIR.scala:145)
	at is.hail.expr.ir.IRParser$$anonfun$table_ir_1$2.apply(Parser.scala:1024)
	at is.hail.expr.ir.IRParser$$anonfun$table_ir_1$2.apply(Parser.scala:1024)
	at scala.Option.getOrElse(Option.scala:121)
	at is.hail.expr.ir.IRParser$.table_ir_1(Parser.scala:1024)
	at is.hail.expr.ir.IRParser$.table_ir(Parser.scala:998)
	at is.hail.expr.ir.IRParser$$anonfun$parse_table_ir$2.apply(Parser.scala:1395)
	at is.hail.expr.ir.IRParser$$anonfun$parse_table_ir$2.apply(Parser.scala:1395)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1384)
	at is.hail.expr.ir.IRParser$.parse_table_ir(Parser.scala:1395)
	at is.hail.expr.ir.IRParser$.parse_table_ir(Parser.scala:1394)
	at is.hail.expr.ir.IRParser.parse_table_ir(Parser.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)



Hail version: 0.2.18-08ec699f0fd4
Error summary: IllegalArgumentException: Can not create a Path from an empty string
DEBUG: 1 running tasks, waiting for next task to finish```

**Comment by mike-w-wilson** [comment]
HGMD path is now optional
